Create main logics & features
estela19/Tetris pull request #1
Opened 2020-01-02 10:20 UTC by estela19

2020-01-02 10:33 UTC, 1cekrim commented on Includes/Tetris/Point.h
> +//    static void GotoXY(const int& x, const int& y);
필요없는 주석이 남아있습니다.

2020-01-02 10:48 UTC, frechele reviewed
확인바랍니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/pattern.h
> +inline Point patterns[7][4][4] =  // ���/ ȸ�� / ������ 4��
주석 한글이 깨집니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/Board.h
> +    bool IsFullRow(std::size_t idx);
const형 method로 하는 게 좋습니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/Point.h
> +    Point operator+(const Point &pt);
operator+는 const형 method로 만들어야합니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/Point.h
> +    static void GotoXY(Point pos);
const Point&로 인자를 받아야 합니다.

2020-01-02 10:48 UTC, JYPark09 commented on Sources/Tetris/Point.cc
> +    return tmp;
```
return Point(x_ + pt.x_, y_ + pt.y_);
```

로 고치는 건 어떨까요?

2020-01-02 10:48 UTC, JYPark09 commented on Sources/Tetris/Screen.cc
> +        ORIGINAL std::cout << "��";
인코딩이 깨집니다.

2020-01-02 10:48 UTC, JYPark09 commented on Sources/Tetris/Screen.cc
> +            }
인코딩이 깨집니다.

2020-01-02 10:48 UTC, JYPark09 commented on Sources/Tetris/Screen.cc
> +        }
인코딩이 깨집니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/Screen.h
> +    static void PrintSpace(Tetrimino& tetrimino);
const Tetriminio&형으로 인자를 받는게 좋을 것 같습니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/game.h
> +    static const std::size_t scrheight_;
constexpr을 사용하는 건 어떨까요?

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/game.h
> +    std::size_t GetScrHeight();
const형 method로 하는 게 좋습니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/game.h
> +    std::size_t GetLevel();
const형 method로 만드는 게 낫습니다.

2020-01-02 10:48 UTC, JYPark09 commented on Includes/Tetris/game.h
> +    bool IsGameOver();
const형 method로 만드는 게 낫습니다.

2020-01-02 10:48 UTC, JYPark09 commented on Sources/Tetris/Board.cc
> +    board.clear();
vector::clear를 호출하면 vector 안의 모든 요소가 지워집니다.

2020-01-02 11:30 UTC, estela19 commented on Includes/Tetris/Point.h
> +//    static void GotoXY(const int& x, const int& y);
불필요한 주석 제거했습니다

2020-01-02 11:31 UTC, estela19 commented on Includes/Tetris/Board.h
> +    bool IsFullRow(std::size_t idx);
const형 method로 변경했습니다.

2020-01-02 11:31 UTC, estela19 commented on Includes/Tetris/Point.h
> +    Point operator+(const Point &pt);
const형 method로 변경했습니다.

2020-01-02 11:31 UTC, estela19 commented on Includes/Tetris/Point.h
> +    static void GotoXY(Point pos);
const & 형식으로 변경했습니다.

2020-01-02 11:32 UTC, estela19 commented on Sources/Tetris/Point.cc
> +    return tmp;
위 형식대로 수정했습니다.

2020-01-02 11:33 UTC, estela19 commented on Includes/Tetris/Screen.h
> +    static void PrintSpace(Tetrimino& tetrimino);
const & 형 인자를 받도록 변경했습니다

2020-01-02 11:34 UTC, estela19 commented on Includes/Tetris/game.h
> +    static const std::size_t scrheight_;
const를 constexpr로 모두 변경했습니다.

2020-01-02 11:34 UTC, estela19 commented on Includes/Tetris/game.h
> +    std::size_t GetScrHeight();
const형 method로 변경했습니다.

2020-01-02 11:34 UTC, estela19 commented on Includes/Tetris/game.h
> +    std::size_t GetLevel();
const형 method로 변경했습니다.

2020-01-02 11:34 UTC, estela19 commented on Includes/Tetris/game.h
> +    bool IsGameOver();
const형 method로 변경했습니다.

2020-01-02 11:42 UTC, estela19 commented on Includes/Tetris/Board.h
> +    bool IsFullRow(std::size_t idx);
board를 변경해야하기 때문에 const형 method로 만들긴 어렵습니다.

2020-01-02 11:44 UTC, estela19 commented on Includes/Tetris/pattern.h
> +inline Point patterns[7][4][4] =  // ���/ ȸ�� / ������ 4��
영문으로 수정했습니다.

2020-01-02 11:47 UTC, estela19 commented on Sources/Tetris/Screen.cc
> +        ORIGINAL std::cout << "��";
인코딩은 차후에 해결하도록 하겠습니다.

2020-01-02 11:47 UTC, estela19 commented on Sources/Tetris/Screen.cc
> +            }
인코딩은 차후에 해결하도록 하겠습니다.

2020-01-02 11:47 UTC, estela19 commented on Sources/Tetris/Screen.cc
> +        }
인코딩은 차후에 해결하도록 하겠습니다.

2020-01-03 13:21 UTC, ydk1104 commented on Sources/Tetris/Screen.cc
> +        }
52 to 79줄과 중복됩니다. 따로 함수를 만들어 처리하는게 나을것 같습니다.

2020-01-03 13:21 UTC, ydk1104 commented on Sources/Tetris/Tetrimino.cc
> +    Pos.SetY(Pos.GetY() + 1);
아랫줄에서 while(MoveDown())하면 필요없지 않나요?

2020-01-03 13:21 UTC, ydk1104 commented on Sources/Tetris/Board.cc
> +            break;
break 대신 return false;를 사용하고, isfull변수는 쓰지 않아도 될 것 같습니다. isValid 함수와 구현 방식이 달라 통일하는게 깔끔할듯싶네요.

2020-01-05 05:45 UTC, estela19 commented on Sources/Tetris/Board.cc
> +            break;
isfull 변수를 제거하고 return하는 방식으로 변경했습니다.

2020-01-05 05:46 UTC, estela19 commented on Sources/Tetris/Tetrimino.cc
> +    Pos.SetY(Pos.GetY() + 1);
해당 코드를 삭제했습니다. 좋은 지적 감사합니다.

2020-01-05 05:46 UTC, estela19 commented on Sources/Tetris/Screen.cc
> +        }
비교하는 인자가 tetrimino 타입과 board타입이라서 따로 두는 편이 나을 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 requested changes
please confirm

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Tetrimino.cc
> +    std::size_t maxY = Game::Get().GetHeight();
Game::Width_, Game::Height_가 좋을 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 commented on Includes/Tetris/game.h
> +    std::size_t GetScrHeight() const;
getter가 필요할까요?

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Game.cc
> +}
getter가 필요할까요?

2020-01-05 14:18 UTC, ydk1104 commented on Includes/Tetris/game.h
> +    static constexpr std::size_t scrheight_ = height_ + 1;
public을 위로 올리는게 더 이쁠 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Tetrimino.cc
> +        Rtype = static_cast<RotateType>(++tmp);
tmp를 만든 이유가 있나요? Rtype = static_cast<RotateType>(static_cast<int>(Rtype)+1);로 해도될것같습니다.
추가로, 괄호 안을 (static_cast<int>(Rtype)+1)%4로 쓰면 LEFT를 따로 처리해줄 필요도 없겠네요.

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Game.cc
> +        }
while( isGameOver == false)로 쓰면 될 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Game.cc
> +}
return clearCnt == 10;
return minBlockPosY <= 0;
으로도 쓸 수 있을 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Game.cc
> +        minY = (minY < tetriY ? minY : tetriY);
minY = std::min(minY, tetriY)를 쓰는건 어떨까요? 더불어, 이렇게 쓰면 minY = std::min(minY, (tetrimino.GetType() + i)-> GetY());로 써도 될 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Game.cc
> +    minBlockPosY = (minY < minBlockPosY ? minY : minBlockPosY);
혹은, 처음부터 minBlockPosY = std::min(minBlockPosY, (tetrimino.GetType() + i)->GetY());로 써도 될 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Game.cc
> +    Point tmp(tetrimino->GetPos().GetX(), tetrimino->GetPos().GetY());
tmp(tetrimino->GetPos())가 좋을 것 같습니다.

2020-01-05 14:18 UTC, ydk1104 commented on Sources/Tetris/Game.cc
> +    }
constexpr int LineScore[5] = {0, 100, 200, 500, 1000};
AddScore(Score[lines]);로 같은식으로 쓸수도 있습니다.

2020-01-06 06:06 UTC, estela19 commented on Sources/Tetris/Game.cc
> +    }
다음부터 참고하도록 하겠습니다.

2020-01-06 06:07 UTC, estela19 commented on Sources/Tetris/Game.cc
> +    Point tmp(tetrimino->GetPos().GetX(), tetrimino->GetPos().GetY());
복사생성자를 부르는 방식으로 수정했습니다.

2020-01-06 06:07 UTC, estela19 commented on Sources/Tetris/Game.cc
> +    minBlockPosY = (minY < minBlockPosY ? minY : minBlockPosY);
min이 window 자체 매크로와 꼬여서 삼항연산자를 사용했습니다.

2020-01-06 06:08 UTC, estela19 commented on Includes/Tetris/game.h
> +    static constexpr std::size_t scrheight_ = height_ + 1;
변수끼리 모아두는 편을 선호해서 저렇게 두었습니다.

2020-01-06 06:09 UTC, estela19 commented on Sources/Tetris/Game.cc
> +}
확인 후 제거했습니다. 좋은지적 감사합니다.

2020-01-06 06:09 UTC, estela19 commented on Includes/Tetris/game.h
> +    std::size_t GetScrHeight() const;
확인 후 제거했습니다.

2020-01-06 06:10 UTC, estela19 commented on Sources/Tetris/Tetrimino.cc
> +    std::size_t maxY = Game::Get().GetHeight();
getter를 없애고 직접 변수를 부르는 방식으로 변경했습니다.

2020-01-06 06:10 UTC, estela19 commented on Sources/Tetris/Tetrimino.cc
> +        Rtype = static_cast<RotateType>(++tmp);
r-value 오류가 나서 저렇게 처리했으나 +1로 처리하면 될 것 같아 수정했습니다. 좋은지적 가마합니다.

2020-01-06 06:12 UTC, estela19 commented on Sources/Tetris/Game.cc
> +        }
'''
while(!isGameOver)
'''
로 수정했습니다.

2020-01-06 06:13 UTC, estela19 commented on Sources/Tetris/Game.cc
> +}
다음부터 참고하겠습니다.

2020-01-06 06:15 UTC, estela19 commented on Sources/Tetris/Screen.cc
> +        }
다음부터 참고하겠습니다.

2020-01-06 06:16 UTC, merged